version: '3.8'

services:
  wireguard:
    build:
      context: .
    container_name: wireguard-server
    cap_add:
      - NET_ADMIN
    privileged: true
    network_mode: "host"
    volumes:
      - ./wireguard/server.conf:/etc/wireguard/server.conf
    restart: unless-stopped
